%YAML:1.0

# Camera intrinsics
IMAGE_WIDTH: 752
IMAGE_HEIGHT: 480
CAMERA_MATRIX: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 694.913664, 0., 380.223364, 0., 695.221797,
       256.961167, 0., 0., 1. ]
DISTORTION_COEFFICIENTS: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -0.053663, 0.074794, -0.000028, 0.001380, 0.000000 ]

# Calibration configures
MARK_SIZE: 243
NUM_FRAME: 5140

DATASET_THRESH_KF_ODOROT: 0.1
DATASET_THRESH_KF_ODOLIN: 100

CALIB_ODOLIN_ERRR: 0.01
CALIB_ODOLIN_ERRMIN: 1
CALIB_ODOROT_ERRR: 0.01
CALIB_ODOROT_ERRRLIN: 1.67e-6
CALIB_ODOROT_ERRMIN: 1.67e-3
CALIB_AMKZ_ERRRZ: 0.05
CALIB_AMKZ_ERRMIN: 1
CALIB_AMKXY_ERRRZ: 0.01
CALIB_AMKXY_ERRMIN: 1

MAPPUB_SCALE_RATIO: 300
